AWSTemplateFormatVersion: "2010-09-09"
Resources:
  FondeskVoiceMessageStaging:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: "yukure-production-bucket"
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: "AES256"
            BucketKeyEnabled: false
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
