name: Release Workflow
on:
  push:
    tags:
      - 'v*'
env:
  AWS_ROLE_ARN: arn:aws:iam::608092561803:role/yukure-admin-for-github-actions
  AWS_REGION: ap-northeast-1
  SLACK_WEBHOOK_URL: https://hooks.slack.com/services/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
permissions:
  id-token: write
  contents: read
jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          role-session-name: deploy-role-session
          aws-region: ${{ env.AWS_REGION }}
      - name: Get Caller Identity
        run: aws sts get-caller-identity
      - name: Deploy to AWS CloudFormation
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: StagingStack
          template: staging.yml
          no-fail-on-empty-changeset: "1"
      - name: slack-send
        uses: slackapi/slack-github-action@v1.16.0
        env:
          SLACK_WEBHOOK_URL: ${{ env.SLACK_WEBHOOK_URL }}
  deploy-production:
    runs-on: ubuntu-latest
    environment: prodaction
    needs: deploy-staging
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          role-session-name: deploy-role-session
          aws-region: ${{ env.AWS_REGION }}
      - name: Get Caller Identity
        run: aws sts get-caller-identity
      - name: Deploy to AWS CloudFormation
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: ProductionStack
          template: production.yml
          no-fail-on-empty-changeset: "1"
